In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [245]:
data = pd.read_csv('./data/train.csv')
test_data = pd.read_csv('./data/test.csv')

N = 80000
data = shuffle(data, random_state = 0)
data = data.iloc[:N, :]

status = data["Violation Status"].unique()
license_type = list(set(test_data["License Type"].unique()) | set(data["License Type"].unique()))
violation = list(set(test_data["Violation"].unique()) | set(data["Violation"].unique()))
county = list(set(test_data["County"].unique()) | set(data["County"].unique()))
issu_agency = list(set(test_data["Issuing Agency"].unique()) | set(data["Issuing Agency"].unique()))
state = list(set(test_data["State"].unique()) | set(data["State"].unique()))
# data.head(10)

# status_tst = test_data["Violation Status"].unique()
# license_type = test_data["License Type"].unique()
# violation = test_data["Violation"].unique()
# county = test_data["County"].unique()
# issu_agency = test_data["Issuing Agency"].unique()
# state = test_data["State"].unique()

In [246]:
print("len(status) = ", len(status))
print("license_type = ", len(license_type))
# print(status)
        
for i in range(len(status)):
    data["Violation Status"].replace(status[i],i,inplace=True)
    
for i in range(len(license_type)):
    data["License Type"].replace(license_type[i],i,inplace=True)
    
for i in range(len(violation)):
    data["Violation"].replace(violation[i],i,inplace=True)

for i in range(len(county)):
    data["County"].replace(county[i],i,inplace=True)
    
for i in range(len(issu_agency)):
    data["Issuing Agency"].replace(issu_agency[i],i,inplace=True)
    
for i in range(len(state)):
    data["State"].replace(state[i],i,inplace=True)

data.drop(labels=None,axis=1, index=None, columns="Plate", inplace=True)
data.drop(labels=None,axis=1, index=None, columns="Summons Number", inplace=True)
data.drop(labels=None,axis=1, index=None, columns="Issue Date", inplace=True)
data.drop(labels=None,axis=1, index=None, columns="Violation Time", inplace=True)
data.drop(labels=None,axis=1, index=None, columns="Judgment Entry Date", inplace=True)
data.drop(labels=None,axis=1, index=None, columns="ID", inplace=True)

# data.head(10)

print(data.shape)

len(status) =  14
license_type =  60
(80000, 13)

In [247]:
for i in range(len(license_type)):
    test_data["License Type"].replace(license_type[i],i,inplace=True)
    
for i in range(len(violation)):
    test_data["Violation"].replace(violation[i],i,inplace=True)

for i in range(len(county)):
    test_data["County"].replace(county[i],i,inplace=True)
    
for i in range(len(issu_agency)):
    test_data["Issuing Agency"].replace(issu_agency[i],i,inplace=True)
    
for i in range(len(state)):
    test_data["State"].replace(state[i],i,inplace=True)

test_data.drop(labels=None,axis=1, index=None, columns="Plate", inplace=True)
test_data.drop(labels=None,axis=1, index=None, columns="Summons Number", inplace=True)
test_data.drop(labels=None,axis=1, index=None, columns="Issue Date", inplace=True)
test_data.drop(labels=None,axis=1, index=None, columns="Violation Time", inplace=True)
test_data.drop(labels=None,axis=1, index=None, columns="Judgment Entry Date", inplace=True)
test_data.drop(labels=None,axis=1, index=None, columns="ID", inplace=True)

X_tst_final = test_data.iloc[:, :]
print(X_tst_final.shape)

(200000, 12)

In [248]:
print("len(data.columns)", len(data.columns))
X = data.iloc[:, :-1]
y = data.iloc[:, -1]
le = LabelEncoder()
y = le.fit_transform(y)
X_trn, X_tst, y_trn, y_tst = train_test_split(X, y, test_size=0.3, random_state=42)
X_trn.head(10)

len(data.columns) 13

,State,License Type,Violation,Fine Amount,Penalty Amount,Interest Amount,Reduction Amount,Payment Amount,Amount Due,Precinct,County,Issuing Agency
25675,36,36,5,115,0,0.00,0.00,115.00,0.0,1,1,9
61050,1,36,23,115,0,0.00,0.00,115.00,0.0,106,5,9
46089,1,36,18,65,10,0.00,3.99,71.01,0.0,66,8,9
2662,2,36,79,65,0,0.00,0.00,0.00,65.0,1,1,9
45637,1,36,5,115,60,0.99,0.04,175.95,0.0,44,7,9
61263,1,16,58,115,0,0.00,23.00,92.00,0.0,14,1,9
63350,1,36,55,45,0,0.00,0.00,45.00,0.0,61,8,15
53748,1,16,63,115,0,0.00,50.00,65.00,0.0,75,8,9
49136,1,16,22,65,0,0.00,0.00,0.00,65.0,1,1,9
15517,1,30,79,65,0,0.00,0.00,65.00,0.0,17,1,9

In [249]:
print("X_trn.shape = ",X_trn.shape)

X_trn.shape =  (56000, 12)

In [250]:
##Bagging and Forest Tree
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

clf = BaggingClassifier(base_estimator = DecisionTreeClassifier(criterion = "entropy"), 
                         n_estimators  = 5)

model = clf.fit(X_trn, y_trn)
y_pre_tst = clf.predict(X_tst)
y_pre_trn = clf.predict(X_trn)
Err_Train = accuracy_score(y_pre_trn, y_trn)
Err_Test = accuracy_score(y_pre_tst, y_tst)
print("Err_Train: ", Err_Train)
print("Err_Test: ", Err_Test)

Err_Train:  0.9278035714285714
Err_Test:  0.8577083333333333

In [229]:
#Write data to file
test_data_final = pd.read_csv('./data/test.csv')
df_sub = pd.DataFrame({'ID':test_data_final["ID"],'Prediction':y_pre_tst_final})
for i in range(len(status)):
    df_sub["Prediction"].replace(i,status[i],inplace=True)
df_sub.to_csv("./data/sub1.csv",index=False,sep=',')

In [ ]:
clf = AdaBoostClassifier(base_estimator = DecisionTreeClassifier(criterion = "entropy", max_depth = 100), 
                             n_estimators  = indices[i])